version: '3.10'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - '127.0.0.1:3000:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      services-network:
        aliases:
          - db
  web:
    container_name: ltw
    #if the image is not necessary to build, comment it out. Image will be pull from the repository. 
    #build: .  
    image: ghcr.io/miku0129/docker-ltw/ltw:latest
    depends_on:
      - db
    ports:
      - '127.0.0.1:8000:8080'
    environment:
      POSTGRES_URL: postgresql://postgres:postgres@db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PW: postgres
      POSTGRES_DB: postgres
    links: 
      - db
    volumes:
      - './:/src'
    networks:
      services-network:
        aliases:
          - web

volumes: 
  db: 
    driver: local

networks:
  services-network:
    name: services-network
    driver: bridge
