"""create password table modify user_profile_id column

Revision ID: 194ea6f1b861
Revises: 42289842c257
Create Date: 2022-11-20 12:01:21.070277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '194ea6f1b861'
down_revision = '42289842c257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    passwords = op.create_table('passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.alter_column('users_profiles', 'user_profile_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    
    op.bulk_insert(passwords, [
        {'id':1, 'user_id':'1', 'password':'pass1'},
        {'id':2, 'user_id':'2', 'password':'pass2'},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_profiles', 'user_profile_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_table('passwords')
    # ### end Alembic commands ###
