"""Create users_profile table

Revision ID: 42289842c257
Revises: 
Create Date: 2022-11-20 11:43:48.967260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42289842c257'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users_profiles = op.create_table('users_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('main_language', sa.Integer(), nullable=True),
    sa.Column('is_supporter', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name'),
    sa.UniqueConstraint('user_profile_id')
    )
    op.bulk_insert(users_profiles, [
        {'id':1, 'user_profile_id': 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'user_name':'matta','email': 'matta@zmail.com', 'gender':1, 'main_language':1 , 'is_supporter':True,'is_admin':True },
        {'id':2, 'user_profile_id': 'b0EEBC99-9C0B-4EF8-BB6D-6BB9BD380b11', 'user_name':'luddy','email': 'luddy@zmail.com', 'gender':1, 'main_language':2 , 'is_supporter':False, 'is_admin':False},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_profiles')
    # ### end Alembic commands ###
