"""Initial migration

Revision ID: 454869b5636f
Revises: 
Create Date: 2022-11-19 15:12:22.503754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454869b5636f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(user_table, [
        {'id':1, 'name':'miku'},
        {'id':2, 'name':'ludo'},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
