"""modify type user_id user_profile_id

Revision ID: a1bbe400684b
Revises: 194ea6f1b861
Create Date: 2022-11-20 20:42:09.008732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1bbe400684b'
down_revision = '194ea6f1b861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('passwords', 'user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users_profiles', 'user_profile_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_profiles', 'user_profile_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('passwords', 'user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
